//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensWebAPI.Models.DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_order { get; set; }
        public string Recipe { get; set; }
        public int Amount { get; set; }
    }
}
