//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ressuply
    {
        public int ID_warehouse { get; set; }
        public int ID_compartment { get; set; }
        public int ID_feedstock { get; set; }
        public System.DateTime DateOfRessuply { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> DateOfExpiration { get; set; }
    
        public virtual WarehouseStorage WarehouseStorage { get; set; }
    }
}
