//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiemensWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int ID_supply { get; set; }
        public int ID_compartment { get; set; }
        public int ID_feedstock { get; set; }
        public System.DateTime DateOfRessuply { get; set; }
<<<<<<< HEAD:SiemensWebAPI/SiemensWebAPI/Models/Ressuply.cs
        public Nullable<System.DateTime> DateOfExpiration { get; set; }
        public string Quantity_Bought { get; set; }
=======
        public string Quantity { get; set; }
        public System.DateTime DateOfExpiration { get; set; }
>>>>>>> feature/DatabaseModels:SiemensWebAPI/SiemensWebAPI/Models/Supply.cs
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
